### ISSUE TITLE
Is this currently working/live?

### ISSUE THREAD

**Issue by drevicko** [Perlence/dropbox-via-webdav#1]
Hi Perlence, are you using this currently? Do you know if it currently works? I see the last commit is 3 years ago and things may have changed on several fronts.

**Comment by Perlence** [comment]
Hey @drevicko! No, I haven't been using it for all this time, I don't know if it still works. You are welcome to try!

**Comment by drevicko** [comment]
Hi @Perlence (:

Turns out I no longer need it (I wanted to sync my Zotero attachment storage to dropbox, but found out it can be done with a normal file system symlink instead :).

My guess is it'll need a little polishing - dependencies, dropbox api, web-dav itself may well have changed a little since! If I need it some time in the future, I'll have a go. In the meantime, if someone is in a hurry, there's a commercial service "DropDav" that seems ok.
