### ISSUE TITLE
'module' object has no attribute 'ACCESS_TOKENS'

### ISSUE THREAD

**Issue by MrJollyOlliMan** [Perlence/dropbox-via-webdav#2]
Hi,
do anybody use this client already? I wand to use this together with my home server & router, to provide a dropbox in our local network.
I started this with a test session on a RasPi. During this session I run in troubles. I could realise all points of the readme.md but starting the `wsgidav` isn't possible. I already run in problems with the config file.

> Failed to read configuration file: /home/pi/Downloads/dropbox-via-webdav/wsgidav.conf
> Due to AttributeError: 'module' object has no attribute 'ACCESS_TOKENS'
> 
> Traceback (most recent call last):
>   File "/usr/local/bin/wsgidav", line 11, in <module>
>     load_entry_point('WsgiDAV==1.1.0', 'console_scripts', 'wsgidav')()
>   File "/home/pi/.local/lib/python2.7/site-packages/wsgidav/server/run_server.py", line 506, in run
>     config = _initConfig()
>   File "/home/pi/.local/lib/python2.7/site-packages/wsgidav/server/run_server.py", line 222, in _initConfig
>     fileConf = _readConfigFile(config_file, temp_verbose)
>   File "/home/pi/.local/lib/python2.7/site-packages/wsgidav/server/run_server.py", line 182, in _readConfigFile
>     configmodule = imp.load_source("configuration_module", config_file)
>   File "/home/pi/Downloads/dropbox-via-webdav/wsgidav.conf", line 121, in <module>
>     for shareName, accessToken in config.ACCESS_TOKENS.items():
> AttributeError: 'module' object has no attribute 'ACCESS_TOKENS'

I also saw this effect with the others attributes CONSUMER_KEY & CONSUMER_SECRET during a short test. The config.py & config.json file are in the same directory as wsgidav.conf.

Any ideas why this stops with errors? thx

**Comment by Perlence** [comment]
Hey @MrJollyOlliMan,

Looks like your `config.json` is missing `ACCESS_TOKENS`. Please, start `python get-access-token.py` and follow the instructions.

**Comment by MrJollyOlliMan** [comment]
Hi Perlence,
I used the `get_access_token.py` script to generate the token and add this in my `config.json`, see below.
```
{
    "CONSUMER_KEY": "XXXXXX",
    "CONSUMER_SECRET": "XXXXXX",
    "ACCESS_TOKENS": {
        "olli": "XXXXXXXXXXXXXX"
        }
}
```
I made a test with `print(config.CONSUMER_KEY)` and the same with `CONSUMER_SECRET` into `wsgidav.conf` and have the same error:
```
AttributeError: 'module' object has no attribute 'CONSUMER_KEY'
```
Looks like `wsgidav.conf` has no access to `config.py` and/or `config.json`. These three files are in the same directory as `get_access_token.py` and this script could read the first two attributes of `config.json`.
I didn't change anything in `wsgidav.conf`.

That's why I'm so clueless. I started `wsgidav` as pi. Do any file needs some special rights or onwerships?

**Comment by Perlence** [comment]
Perhaps you have a system-level Python module called `config`?

This line here is supposed to import local module `config.py` https://github.com/Perlence/dropbox-via-webdav/blob/master/dropbox_dav_provider.py#L11

**Comment by MrJollyOlliMan** [comment]
The global `config` module was the correct hint, after uninstall the local one works. 👍 

Next step will be dropbox APIv2 :-)

**Comment by Perlence** [comment]
I'm glad it worked! I'll close this.
